<?php

namespace Test\Ease\SQL;

use Ease\SQL\Debugger;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2022-10-03 at 23:41:45.
 */
class DebuggerTest extends \PHPUnit\Framework\TestCase {

    /**
     * @var Debugger
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void {
        $this->object = new Debugger();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void {
        
    }

}
