<?php

namespace Test\Ease\SQL;

use Ease\SQL\Engine;
use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2020-05-10 at 14:47:05.
 */
class EngineTest extends TestCase {

    /**
     * @var Engine
     */
    protected $object;
    protected $lastId = null;

    private function updateLastId() {
        $this->lastId = $this->object->listingQuery()->orderBy('id DESC')->limit(1)->fetchColumn(0);
    }

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void {

        $this->object = new Engine(null, [
            'myTable' => 'test',
            'createColumn' => 'created',
            'lastModifiedColumn' => 'updated',
            'nameColumn' => 'name'
        ]);

        $this->updateLastId();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void {
        
    }

    /**
     * Test Constructor
     *
     * @covers Ease\SQL\Engine::__construct
     */
    public function testConstructor() {
        $classname = get_class($this->object);

        // Get mock, without the constructor being called
        $mock = $this->getMockBuilder($classname)
                ->disableOriginalConstructor()
                ->getMockForAbstractClass();
        $mock->__construct(null, ['debug' => true]);
        $mock->__construct(1, ['autoload' => true, 'myTable' => 'test']);
        $this->assertEquals('a', $mock->getDataValue('value'));
        $mock->__construct(['name' => 'bar'], ['autoload' => true, 'myTable' => 'test']);
        $this->assertEquals('b', $mock->getDataValue('value'));
        $mock->__construct('', ['autoload' => true, 'myTable' => 'test', 'keyColumn' => 'value']);
        $this->assertEquals(2, $mock->getDataValue('id'));
    }

    /**
     * @covers Ease\SQL\Engine::getRecordName
     */
    public function testGetRecordName() {
        $this->object->loadFromSQL(1);
        $this->assertEquals('foo', $this->object->getRecordName());
    }

    /**
     * @covers Ease\SQL\Engine::setmyTable
     */
    public function testSetmyTable() {
        $this->assertEquals('', $this->object->setmyTable('test'));
    }

    /**
     * @covers Ease\SQL\Engine::getMyTable
     */
    public function testGetMyTable() {
        $this->object->setmyTable('test');
        $this->assertEquals('test', $this->object->getMyTable());
    }

    /**
     * @covers Ease\SQL\Engine::searchColumns
     */
    public function testSearchColumns() {
        $this->assertNotEmpty($this->object->searchColumns('bar', ['name'], 1)->fetch());
    }

    /**
     * @covers Ease\SQL\Engine::getAll
     */
    public function testGetAll() {
        $this->assertArrayHasKey(1, $this->object->getAll());
    }

    /**
     * @covers Ease\SQL\Engine::setUp
     */
    public function testSetUp() {
        $this->object->setUp();
        $this->assertNotNull($this->object->dbType);
    }

    /**
     * @covers Ease\SQL\Engine::pdoConnect
     */
    public function testPdoConnect() {
        $this->expectException('\Ease\Exception');
        $this->assertInstanceOf('\PDO', $this->object->pdoConnect(['DB_TYPE' => 'sqlite', 'DB_NAME' => 'nonexist']));
        $this->assertInstanceOf('\PDO', $this->object->pdoConnect(['DB_TYPE' => 'sqlite']));
        $this->expectException('\PDOException');
        $this->assertInstanceOf('\PDO', $this->object->pdoConnect(['DB_TYPE' => 'mysql', 'DB_NAME' => 'localhost']));
        $this->assertInstanceOf('\PDO', $this->object->pdoConnect(['DB_TYPE' => 'postgresql']));
    }

    /**
     * @covers Ease\SQL\Engine::getPdo
     */
    public function testGetPdo() {
        $this->assertInstanceOf('PDO', $this->object->GetPdo());
    }

    /**
     * @covers Ease\SQL\Engine::getFluentPDO
     */
    public function testGetFluentPDO() {
        $this->assertInstanceOf('Envms\FluentPDO\Query', $this->object->getFluentPDO());
    }

    /**
     * @covers Ease\SQL\Engine::listingQuery
     */
    public function testListingQuery() {
        $this->assertInstanceOf('Envms\FluentPDO\Queries\Select', $this->object->listingQuery());
    }

    /**
     * @covers Ease\SQL\Engine::getColumnsFromSQL
     */
    public function testGetColumnsFromSQL() {
        $this->assertEquals([2 => ['id' => 2]], $this->object->getColumnsFromSQL(['id'], ['id' => 2], 'id', 'id'));
    }

    /**
     * @covers Ease\SQL\Engine::getDataFromSQL
     */
    public function testGetDataFromSQL() {
        $this->assertEquals('', $this->object->getDataFromSQL(1));
    }

    /**
     * @covers Ease\SQL\Engine::loadFromSQL
     */
    public function testLoadFromSQL() {
        $this->assertEquals(5, $this->object->loadFromSQL(2));
    }

    /**
     * @covers Ease\SQL\Engine::dbreload
     */
    public function testDbreload() {
        $this->assertEquals('', $this->object->dbreload());
    }

    /**
     * @covers Ease\SQL\Engine::dbsync
     */
    public function testDbsync() {
        $this->object->setData(['name' => 'thrid', 'value' => 'newone']);
        $this->assertTrue($this->object->dbsync());
    }

    /**
     * @covers Ease\SQL\Engine::updateToSQL
     */
    public function testUpdateToSQL() {
        $this->assertEquals(1, $this->object->updateToSQL(['id' => 1, 'name' => 'foo', 'value' => 'updated']));
        $this->object->setData(['id' => 1, 'name' => 'foo', 'value' => 'a']);
        $this->assertEquals(1, $this->object->updateToSQL()); //Reset to Inital value for further testing
        $this->expectException('\Envms\FluentPDO\Exception');
        $this->object->updateToSQL(['id' => 5, 'foo' => 'bar']);
    }

    /**
     * @covers Ease\SQL\Engine::saveToSQL
     */
    public function testSaveToSQL() {
        $this->object->setData(['name' => 'saved', 'value' => 'sure']);
        $this->assertEquals($this->lastId + 1, $this->object->saveToSQL());
        $this->object->setData(['id' => 3, 'name' => 'saved', 'value' => 'sure']);
        $this->assertEquals(3, $this->object->saveToSQL());
    }

    /**
     * @covers Ease\SQL\Engine::insertToSQL
     */
    public function testInsertToSQL() {
        $this->object->setData(['name' => 'xyz', 'value' => 'xxx']);
        $this->assertIsInt($this->object->insertToSQL());
        $this->assertIsInt($this->object->insertToSQL(['name' => 'cfg', 'value' => 'c']));

        $this->expectException('Envms\FluentPDO\Exception');
        $this->object->insertToSQL(['z' => 'e']);
    }

    /**
     * @covers Ease\SQL\Engine::deleteFromSQL
     */
    public function testDeleteFromSQL() {
        $this->object->setData(['id' => $this->lastId]);
        $this->assertEquals(1, $this->object->deleteFromSQL());
    }

    /**
     * @covers Ease\SQL\Engine::takeToData
     */
    public function testTakeToData() {
        $this->assertEquals('', $this->object->takeToData(['a' => 'b'], '2ndLevel'));
    }

}
