<?php

namespace Test\Ease\SQL;

use Ease\SQL\Engine;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2020-05-10 at 14:47:05.
 */
class EngineTest extends \PHPUnit\Framework\TestCase {

    /**
     * @var Engine
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void {
        $this->object = new Engine(null,['myTable'=>'test']);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void {
        
    }

    /**
     * @covers Ease\SQL\Engine::getRecordName
     */
    public function testGetRecordName() {
        $this->assertEquals('', $this->object->GetRecordName());
    }


    /**
     * @covers Ease\SQL\Engine::setmyTable
     */
    public function testSetmyTable() {
        $this->assertEquals('', $this->object->setmyTable('test'));
    }

    /**
     * @covers Ease\SQL\Engine::getMyTable
     */
    public function testGetMyTable() {
        $this->object->setmyTable('test');
        $this->assertEquals('test', $this->object->getMyTable());
    }
    
    
    /**
     * @covers Ease\SQL\Engine::searchColumns
     */
    public function testSearchColumns() {
        $this->assertEquals('', $this->object->searchColumns(['id'], 1));
    }

    /**
     * @covers Ease\SQL\Engine::getAll
     */
    public function testGetAll() {
        $this->assertEquals([], $this->object->getAll());
    }

    /**
     * @covers Ease\SQL\Engine::setUp
     */
    public function testSetUp() {
        $this->assertEquals('', $this->object->setUp());
    }

    /**
     * @covers Ease\SQL\Engine::pdoConnect
     */
    public function testPdoConnect() {
        $this->assertEquals('', $this->object->pdoConnect());
    }

    /**
     * @covers Ease\SQL\Engine::getPdo
     */
    public function testGetPdo() {
        $this->assertEquals('PDO', get_class($this->object->GetPdo()));
    }

    /**
     * @covers Ease\SQL\Engine::getFluentPDO
     */
    public function testGetFluentPDO() {
        $this->assertEquals('', $this->object->GetFluentPDO());
    }

    /**
     * @covers Ease\SQL\Engine::listingQuery
     */
    public function testListingQuery() {
        $this->assertEquals('Query', get_class($this->object->ListingQuery()) );
    }

    /**
     * @covers Ease\SQL\Engine::getColumnsFromSQL
     */
    public function testGetColumnsFromSQL() {
        $this->assertEquals('', $this->object->GetColumnsFromSQL(['id']));
    }

    /**
     * @covers Ease\SQL\Engine::getDataFromSQL
     */
    public function testGetDataFromSQL() {
        $this->assertEquals('', $this->object->GetDataFromSQL());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers Ease\SQL\Engine::loadFromSQL
     */
    public function testLoadFromSQL() {
        $this->assertEquals('', $this->object->LoadFromSQL());
    }

    /**
     * @covers Ease\SQL\Engine::dbreload
     */
    public function testDbreload() {
        $this->assertEquals('', $this->object->Dbreload());
    }

    /**
     * @covers Ease\SQL\Engine::dbsync
     */
    public function testDbsync() {
        $this->assertEquals('', $this->object->Dbsync());
    }

    /**
     * @covers Ease\SQL\Engine::updateToSQL
     */
    public function testUpdateToSQL() {
        $this->assertEquals('', $this->object->updateToSQL());
    }

    /**
     * @covers Ease\SQL\Engine::saveToSQL
     */
    public function testSaveToSQL() {
        $this->assertEquals('', $this->object->saveToSQL());
    }

    /**
     * @covers Ease\SQL\Engine::insertToSQL
     */
    public function testInsertToSQL() {
        $this->assertEquals('', $this->object->insertToSQL());
    }

    /**
     * @covers Ease\SQL\Engine::deleteFromSQL
     */
    public function testDeleteFromSQL() {
        $this->assertEquals('', $this->object->deleteFromSQL());
    }

    /**
     * @covers Ease\SQL\Engine::takeToData
     */
    public function testTakeToData() {
        $this->assertEquals('', $this->object->TakeToData());
    }

}
